language: python
sudo: false

env:
  - LUA="lua=5.2"

before_install:
  - pip install hererocks
  - hererocks env --$LUA -rlatest
  - source env/bin/activate
  - git clone https://github.com/jsalzbergedu/fst-fast-system.git
  - git clone https://github.com/jsalzbergedu/fst-fast.git
  - pushd fst-fast-system
  - luarocks build
  - popd
  - pushd fst-fast
  - luarocks build
  - popd
  - luarocks install luaunit
  - luarocks install luafilesystem
  - luarocks install Lua-cURL
  - luarocks install luacov
  - luarocks install luacov-coveralls

install:
  - luarocks make

script:
  - lua -lluacov test.lua -x testCompilerOutput3

after_success:
  - luacov-coveralls
