language: python
sudo: false

env:
  - LUA="lua=5.2"

before_install:
  - pip install hererocks
  - hererocks env --$LUA -rlatest
  - source env/bin/activate
  - git clone https://github.com/jsalzbergedu/fst-fast-system.git
  - git clone https://github.com/jsalzbergedu/fst-fast.git
  - pushd fst-fast-system
  - luarocks build
  - popd
  - pushd fst-fast
  - luarocks build
  - popd
  - luarocks install luaunit
  - luarocks install luafilesystem

install:
  - luarocks make

script:
  - luarocks test
