language: python
sudo: false

# Based on the .travis.yml config for Moses.

env:
  - LUA="lua=5.2"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin # Add directory with all installed binaries to PATH
  - source lua_install/bin/activate
  - git clone https://github.com/jsalzbergedu/fst-fast-system.git
  - git clone https://github.com/jsalzbergedu/fst-fast.git

install:
  - pushd fst-fast-system
  - luarocks build --tree=lua_install --local
  - popd
  - pushd fst-fast
  - luarocks build --tree=lua_install --local
  - popd
  - luarocks --tree=lua_install install luaunit
  - luarocks --tree=lua_install install luafilesystem

script:
  - luarocks --tree=lua_install test

after_success:
  - luacov-coveralls --exclude $TRAVIS_BUILD_DIR/lua_install
